DIENMAYQUYETTIEN2/Models/InstallmentBillDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIENMAYQUYETTIEN2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentBillDetail
    {
        public int ID { get; set; }
        public int BillID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int InstallmentPrice { get; set; }
    
        public virtual InstallmentBill InstallmentBill { get; set; }
        public virtual Product Product { get; set; }
    }
}

DIENMAYQUYETTIEN2/Areas/Admin/Controllers/InstallmentBillDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DIENMAYQUYETTIEN2.Models;

namespace DIENMAYQUYETTIEN2.Areas.Admin.Controllers
{
    public class InstallmentBillDetailsController : Controller
    {
        private DIENMAYQUYETTIENEntities db = new DIENMAYQUYETTIENEntities();

        // GET: Admin/InstallmentBillDetails
        public ActionResult Index()
        {
            if (Session["insctcashBill"] == null)
        {
                Session["insctcashBill"] = new List<InstallmentBillDetail>();
            }
            return PartialView(Session["insctcashBill"]);
        }
        // GET: Admin/InstallmentBillDetails/Create
        public ActionResult Create()
            {
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductName");
            var model = new InstallmentBillDetail();
            model.ID = 0;
            model.Quantity = 1;
            return PartialView(model);
            }

        public int InstallmentPrice(int ProductID)
        {
            return db.Products.Find(ProductID).InstallmentPrice;
        }

        // POST: Admin/InstallmentBillDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create2(InstallmentBillDetail model)
        {
            if (ModelState.IsValid)
            {
                model.ID = Environment.TickCount;
                model.Product = db.Products.Find(model.ProductID);
                var insctcashBill = Session["insctcashBill"] as List<InstallmentBillDetail>;
                if (insctcashBill == null)
                    insctcashBill = new List<InstallmentBillDetail>();
                insctcashBill.Add(model);
                Session["insctcashBill"] = insctcashBill;
                return RedirectToAction("Create", "InstallmentBills");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductName", model.ProductID);
            return View("Create", model);
        }
        public PartialViewResult Editviewi()
        {

            var a = (Int32)Session["idi"];
            ViewBag.id = a;
            var query = db.InstallmentBillDetails.Where(cbd => cbd.BillID == a).ToList();
            var b = query as List<InstallmentBillDetail>;
            var sum = 0;
            foreach (var chiTiet in b)
            {
                sum += (chiTiet.Quantity * chiTiet.InstallmentPrice);
            }
            Session["Tonggia"] = sum;
            return PartialView(query);
        }
        public ActionResult CreateEditI(int id)
        {
            var a = (Int32)Session["idi"];
            ViewBag.id = a;
            InstallmentBillDetail inscashbilldetail = db.InstallmentBillDetails.Find(id);

            //var query = db.CashBillDetails.Where(cbd => cbd.ID == id).ToList();
            //var b = query as List<CashBillDetail>;
            //var idpd = 0 ;
            //foreach (var chiTiet in b)
            //{
            //     idpd = chiTiet.ProductID;
            //}
            //var query2 = db.Products.Where(cbd => cbd.ID == idpd).ToList();
            //var c = query2 as List<Product>;
            //var orgprice = 0;
            //foreach (var chiTiet in c)
            //{
            //    orgprice = chiTiet.OriginPrice;
            //}


            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductName");

            var model = new InstallmentBillDetail();
            model.BillID = id;
            model.Quantity = 1;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEditI(InstallmentBillDetail ibilldetail)
        {


            var a = (Int32)Session["idi"];

            if (ModelState.IsValid)
            {

                db.InstallmentBillDetails.Add(ibilldetail);
                db.SaveChanges();
                return RedirectToAction("Edit", "InstallmentBills", new { id = a });

            }

            ViewBag.BillID = new SelectList(db.CashBills, "ID", "BillCode", ibilldetail.BillID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductCode", ibilldetail.ProductID);
            return View(ibilldetail);
        }

        // GET: Admin/InstallmentBillDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InstallmentBillDetail installmentBillDetail = db.InstallmentBillDetails.Find(id);
            if (installmentBillDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillID = new SelectList(db.InstallmentBills, "ID", "BillCode", installmentBillDetail.BillID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductCode", installmentBillDetail.ProductID);
            return View(installmentBillDetail);
        }

        // POST: Admin/InstallmentBillDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BillID,ProductID,Quantity,InstallmentPrice")] InstallmentBillDetail installmentBillDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(installmentBillDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillID = new SelectList(db.InstallmentBills, "ID", "BillCode", installmentBillDetail.BillID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductCode", installmentBillDetail.ProductID);
            return View(installmentBillDetail);
        }

        // GET: Admin/InstallmentBillDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InstallmentBillDetail installmentBillDetail = db.InstallmentBillDetails.Find(id);
            if (installmentBillDetail == null)
            {
                return HttpNotFound();
            }
            return View(installmentBillDetail);
        }

        // POST: Admin/InstallmentBillDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InstallmentBillDetail installmentBillDetail = db.InstallmentBillDetails.Find(id);
            db.InstallmentBillDetails.Remove(installmentBillDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/Create.cshtml
@model DIENMAYQUYETTIEN2.Models.InstallmentBillDetail

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}


    @using (Html.BeginForm("Create2", "InstallmentBillDetails")) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal" style="padding: 0px 0%;">
        <h4 style="text-align:center;font-size: 40px;">Add Product in InstallmentBillDetail</h4>
            <hr />
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.ProductID, "ProductName", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProductID)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.InstallmentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.InstallmentPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.InstallmentPrice)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a title="Back" href="@Url.Action("Index")" class="btn btn-danger ">Back to list</a>
                </div>
            </div>
        </div>
    }
    

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/CreateEditI.cshtml
@model DIENMAYQUYETTIEN2.Models.InstallmentBillDetail

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="padding: 0px 6%;">
        <h4>InstallmentBillDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BillID, "BillID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstallmentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstallmentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstallmentPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a title="Back" href="javascript:history.back()" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </div>
}
@section Scripts {
    <script>
    $('#ProductID').change(function () {
            var url = '@Url.Action("SalePrice", "CashBillDetails")';
        url = url + '?ProductID=' + $(this).val();
        $.get(url, function (data) {
                $('#SalePrice').val(data);
        });
    })

    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/Delete.cshtml
@model DIENMAYQUYETTIEN2.Models.InstallmentBillDetail

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>InstallmentBillDetail</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.InstallmentPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.InstallmentPrice)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.InstallmentBill.BillCode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.InstallmentBill.BillCode)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Product.ProductCode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Product.ProductCode)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a title="Back" href="javascript:history.back()" class="btn btn-danger">Cancel</a>
        </div>
        }
    </div>
</body>
</html>

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/Details.cshtml
@model DIENMAYQUYETTIEN2.Models.InstallmentBillDetail

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>InstallmentBillDetail</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.InstallmentPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.InstallmentPrice)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.InstallmentBill.BillCode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.InstallmentBill.BillCode)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Product.ProductCode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Product.ProductCode)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/Edit.cshtml
@model DIENMAYQUYETTIEN2.Models.InstallmentBillDetail

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>InstallmentBillDetail</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.BillID, "BillID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BillID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BillID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.InstallmentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.InstallmentPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.InstallmentPrice, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/Editviewi.cshtml
@model IEnumerable<DIENMAYQUYETTIEN2.Models.InstallmentBillDetail>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Thêm sản phẩm", "CreateEditI", new { id = @ViewBag.id })
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstallmentPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstallmentBill.BillCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.ProductCode)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InstallmentPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InstallmentBill.BillCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductCode)
                </td>
                <td>
                    
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
</body>
</html>

DIENMAYQUYETTIEN2/Areas/Admin/Views/InstallmentBillDetails/Index.cshtml
@model IEnumerable<DIENMAYQUYETTIEN2.Models.InstallmentBillDetail>

@{
    Layout = null;
}

<!DOCTYPE html>

<h2 style="text-align:center;font-size: 40px;">List Products</h2>
    <table class="table" style="width: 70%; margin-left: 250px" >
        <thead>
            <tr>
                <th>
                    Quantity
                </th>
                <th>
                    Product Name
                </th>
                <th>
                    Installment Price
                </th>
                <th>
                    Total
                </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InstallmentPrice)
                </td>
                <td>
                    @(item.Quantity * item.InstallmentPrice)
                </td>

            </tr>
        }

    </table>
    <div>
        <div class="form-group">
            <label class="control-label col-md-2" style="margin-left: 250px">Grand Total</label>
            <div class="col-md-10">
                <input id="GrandTotal2" class="disabled" style="margin-left: 250px" value="@Model.Sum(m => m.InstallmentPrice * m.Quantity)" disabled /> VNĐ
            </div>
        </div>
    </div>