DIENMAYQUYETTIEN2/Areas/Admin/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DIENMAYQUYETTIEN2.Models;
using System.Transactions;
using System.Net;
using System.Data.Entity;
using System.Data;
using System.Web.Security;
using System.Web.Configuration;

namespace DIENMAYQUYETTIEN2.Areas.Admin.Controllers
{
    public class ProductAdminController : Controller
    {
        DIENMAYQUYETTIENEntities db = new DIENMAYQUYETTIENEntities();
        //
        // GET: /Admin/ProductAdmin/
        public ActionResult Index()
        {
            var product = db.Products.Include(b => b.ProductType).ToList();

            if (Session["Username"] != null)
            {
                return View(product);
            }
            else
            {
                return RedirectToAction("Login");
            }
            //return View(product);

        }
        //create
        [HttpGet]
        public ActionResult Create()
        {
            //ViewBag.ProductType = db.ProductTypes.OrderByDescending(x => x.ID).ToList();
            ViewBag.ProductTypeID = new SelectList(db.ProductTypes, "ID", "ProductTypeName");
            if (Session["Username"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
            //return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product p)
        {
            
            CheckBangSanPham(p);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    var pro = new Product();

                pro.ProductCode = p.ProductCode;
                pro.ProductName = p.ProductName;
                pro.ProductType = p.ProductType;
                pro.ProductTypeID = p.ProductTypeID;
                pro.OriginPrice = p.OriginPrice;
                pro.SalePrice = p.SalePrice;
                pro.Status = p.Status;
                pro.Quantity = p.Quantity;
                pro.InstallmentPrice = p.InstallmentPrice;
                pro.Avatar = p.Avatar;
                db.Products.Add(pro);
                db.SaveChanges();
                var path = Server.MapPath("~/App_Data");
                path = path + "/" + pro.ID;
                    if (Request.Files["Avatar"] != null && Request.Files["Avatar"].ContentLength > 0)
                    {
                        Request.Files["Avatar"].SaveAs(path);
                        scope.Complete();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("Avatar", "Chưa có hình ảnh");
                    }
                }

            }
            ViewBag.ProductTypeID = new SelectList(db.ProductTypes, "ID", "ProductTypeName", p.ProductTypeID);
            return View();
        }
        public FileResult Details(int id)
        {
            var path = Server.MapPath("~/App_Data/" + id);
            return File(path, "images");
        }
        //Login
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Account acc)
        {
            if (ModelState.IsValid)
            {
                using (DIENMAYQUYETTIENEntities db = new DIENMAYQUYETTIENEntities())
                {
                    var obj = db.Accounts.Where(a => a.Username.Equals(acc.Username) && a.Password.Equals(acc.Password)).FirstOrDefault();

                    if (obj != null )
                    {
                            Session["Username"] = obj.Username.ToString();
                            Session["FullName"] = obj.FullName.ToString();
                            return RedirectToAction("Index");
                                  
                    }
                }
            }
            return View(acc);
        }
        //Logout
        [HttpPost]
        public ActionResult Logout()
        {   
            Session.Clear();
            Session.Abandon(); // it will clear the session at the end of request
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
                Product bangsanpham = db.Products.Find(ID);
                if (bangsanpham == null)
                {
                return HttpNotFound();
                }
            if (Session["Username"] != null)
            {
                //ViewBag.ProductType = db.ProductTypes.OrderByDescending(x => x.ID).ToList();
                ViewBag.ProductTypeID = new SelectList(db.ProductTypes, "ID", "ProductTypeName", bangsanpham.ProductTypeID);
                return View(bangsanpham);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.ID;
                    if (Request.Files["HinhAnh"] != null && Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);


                    }
                    scope.Complete();
                    return RedirectToAction("Index");

                }
            }
            //ViewBag.ProductType = db.ProductTypes.OrderByDescending(x => x.ID).ToList();
            ViewBag.ProductTypeID = new SelectList(db.ProductTypes, "ID", "ProductTypeName", model.ProductTypeID);
            return View(model);

        }

        private void CheckBangSanPham(Product model)
        {
            
            if (model.OriginPrice < 0)
            {
                ModelState.AddModelError("OriginPrice", "Giá bán phải lớn hơn 0");
            }
            if (model.SalePrice < 0)
            {
                ModelState.AddModelError("SalePrice", "Giá bán phải lớn hơn 0");
            }
            if (model.InstallmentPrice < 0)
            {
                ModelState.AddModelError("InstallmentPrice", "Giá bán phải lớn hơn 0");
            }
            if (model.Quantity < 0)
            {
                ModelState.AddModelError("Quantity", "Giá bán phải lớn hơn 0");
            }

            if (model.ProductName == null)
            {
                ModelState.AddModelError("ProductName", "Tên sản phẩm phải co ký tự");
            }
            
            if (model.ProductName.Length > 30)
            {
                ModelState.AddModelError("ProductName", "Tên sản phẩm phải lớn hơn 30 ký tự");
            }
            
            if (model.ProductName.Trim(' ')=="")
            {
                ModelState.AddModelError("ProductName", "Không được để trống");
            
            }
                
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product bangsanpham = db.Products.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            if (Session["Username"] != null)
            {
                return View(bangsanpham);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product bangsanpham = db.Products.Find(id);
            db.Products.Remove(bangsanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

     
       
    }
}

DIENMAYQUYETTIEN2/Areas/Admin/Views/ProductAdmin/Create.cshtml
@model DIENMAYQUYETTIEN2.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}

<h2 style="text-align:center; padding-top: 20px;"><strong>ADD NEW PRODUCT</strong></h2>


@using (Html.BeginForm("Create", "ProductAdmin",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="padding: 0px 20%;">
        @Html.ValidationSummary(true)


        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductTypeID, "ProductTypeID", new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.ProductTypeID, (IEnumerable<SelectListItem>)ViewData["ProductTypeID"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductTypeID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SalePrice, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.SalePrice, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SalePrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OriginPrice, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.OriginPrice, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OriginPrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstallmentPrice, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.InstallmentPrice, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstallmentPrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.Quantity, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, new { @class = "control-label col-md-2" })
            <div style="width: 200px; padding-left: 15px;">
                @Html.TextBox("Avatar", null, new { type = "file", onchange = "readURL(this)", @class = "form-control" })
                @Html.ValidationMessage("Avatar")
                <img id="HinhSP" src="" width="200" height="200" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Status, new { @class = "type_select" })
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a title="Back" href="@Url.Action("Index")" class="btn btn-danger ">Back to list</a>
            </div>
        </div>
    </div>
}





@section Scripts {
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#HinhSP').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}


DIENMAYQUYETTIEN2/Areas/Admin/Views/ProductAdmin/Delete.cshtml
@model DIENMAYQUYETTIEN2.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}
<div style="height: 20px;"></div>
<div style="display: flex; justify-content: center; flex-direction: row;">
    <h2>Delete Product</h2>
</div>
<div style="display: flex; justify-content: center; flex-direction: row;">
    <h3>Are you sure you want to delete this?</h3>
</div>
<div>
    <div class="dl-horizontal" style="display: flex; justify-content: center; flex-direction: row; margin-top: 30px; font-size: 18px">
        <div>
            <dl style="display: flex;">
                <dt>
                    @Html.DisplayNameFor(model => model.ProductCode):
                </dt>
                &nbsp;
                <dd>
                    @Html.DisplayFor(model => model.ProductCode)
                </dd>
            </dl>
            <dl style="display: flex;">
                <dt>
                    @Html.DisplayNameFor(model => model.ProductName):
                </dt>
                &nbsp;
                <dd>
                    @Html.DisplayFor(model => model.ProductName)
                </dd>
            </dl>
            <dl style="display: flex;">
                <dt>
                    @Html.DisplayNameFor(model => model.SalePrice):
                </dt>
                &nbsp;
                <dd>
                    @Html.DisplayFor(model => model.SalePrice)
                </dd>
            </dl>
            <dl style="display: flex;">
                <dt>
                    @Html.DisplayNameFor(model => model.OriginPrice):
                </dt>
                &nbsp;
                <dd>
                    @Html.DisplayFor(model => model.OriginPrice)
                </dd>
            </dl>
            <dl style="display: flex;">
                <dt>
                    @Html.DisplayNameFor(model => model.InstallmentPrice):
                </dt>
                &nbsp;
                <dd>
                    @Html.DisplayFor(model => model.InstallmentPrice)
                </dd>
            </dl>
            <dl style="display: flex;">
                <dt>
                    @Html.DisplayNameFor(model => model.Quantity):
                </dt>
                &nbsp;
                <dd>
                    @Html.DisplayFor(model => model.Quantity)
                </dd>
            </dl>
            <div class="dl-horizontal" style="display: flex; justify-content: center; flex-direction: row; margin-top: 30px;">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-primary" />
                        <a title="Back" href="@Url.Action("Index")" class="btn btn-danger ">Back to list</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

DIENMAYQUYETTIEN2/Areas/Admin/Views/ProductAdmin/Edit.cshtml
@model DIENMAYQUYETTIEN2.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}

<h2 style="text-align:center; padding-top: 20px;"><strong>EDIT PRODUCT</strong></h2>

@using (Html.BeginForm("Edit", "ProductAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="padding: 0px 20%;">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, htmlAttributes: new { @class = "control-label col-md-2"  })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ProductCode, new { @class = "form-control", @readonly = "readonly"})
                @Html.ValidationMessageFor(model => model.ProductCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductTypeID, "ProductTypeID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("ProductTypeID", new SelectList(ViewBag.ProductType, "ID", "ProductTypeName"))*@
                @Html.DropDownListFor(model => model.ProductTypeID, (IEnumerable<SelectListItem>)ViewData["ProductTypeID"], new { @class = "form-control" })   
                @Html.ValidationMessageFor(model => model.ProductTypeID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SalePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SalePrice, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SalePrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OriginPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.OriginPrice, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OriginPrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstallmentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.InstallmentPrice, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstallmentPrice)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("HinhAnh", "Hình sản phẩm", new { @class = "control-label col-md-2" })
            <div style="width: 200px; padding-left: 15px;">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this);", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="@Url.Action("Details", new { id = Model.ID })" width="200" height="200" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a title="Back" href="@Url.Action("Index")" class="btn btn-danger ">Back to list</a>
            </div>
        </div>
    </div>
}

<script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#HinhSP').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

DIENMAYQUYETTIEN2/Areas/Admin/Views/ProductAdmin/Index.cshtml
@model IEnumerable<DIENMAYQUYETTIEN2.Models.Product>

@{
ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_Layout.cshtml";
}
<h2 style="text-align:center; padding-top: 20px;" class="title"><strong>MANAGE PRODUCT</strong></h2>


<p style="display: flex; justify-content: flex-end; padding-right: 35px;">
    <a href="@Url.Action("Create")" class="btn btn-primary">ADD NEW PRODUCT</a>
</p>
<div class="card mb-3">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Product Code</th>
                        <th>Product Name</th>
                        <th>Sale Price</th>
                        <th>Origin Price</th>
                        <th>Installment Price</th>
                        <th>Quantity</th>
                        <th>Avatar</th>
                        <th>Status</th>
                        <th>ProductID</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Product Code</th>
                        <th>Product Name</th>
                        <th>Sale Price</th>
                        <th>Origin Price</th>
                        <th>Installment Price</th>
                        <th>Quantity</th>
                        <th>Avatar</th>
                        <th>Status</th>
                        <th>ProductID</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SalePrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OriginPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.InstallmentPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Quantity)
                            </td>
                            <td>
                                <img src="@Url.Action("Details", new { id = item.ID })" width="150" height="100" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductType.ProductTypeName)
                            </td>
                            <td>
                                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                                <a title="Sửa" href="@Url.Action("Edit", new { id = item.ID})" class="btn btn-primary ">
                                    <i class="fas fa-edit"></i>
                                </a> 
                                @*<a title="Thông tin" href="@Url.Action("Details", new { id = item.ID})" class="btn btn-success glyphicon glyphicon-file"></a> |*@
                                <a title="Xóa" href="@Url.Action("Delete", new { id = item.ID})" class="btn btn-danger " style="margin-top:20px;">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
        

DIENMAYQUYETTIEN2/Areas/Admin/Views/ProductAdmin/Login.cshtml
@model DIENMAYQUYETTIEN2.Models.Account
@{
    ViewBag.Title = "Login";
    
}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/images/Logo_QT.jpg" alt="IMG">
					<div>    QUYET TIEN electronics Store</div>
					
				</div>
				@using (Html.BeginForm("Login", "ProductAdmin", FormMethod.Post))
				{

				<form class="login100-form validate-form">
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						@Html.TextBoxFor(a => a.Username, new {name="email",placeholder="User", @class = "input100" })
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						@Html.PasswordFor(a => a.Password, new {name="pass",type="password",placeholder="Password", @class = "input100" })
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="#">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			} 
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="~/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="~/js/main.js"></script>

</body>
</html>